# Generated by Django 5.1.6 on 2025-04-12 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_slug_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_discription',
            new_name='product_desription',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_imgage',
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='catgory/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='color_variant',
            field=models.ManyToManyField(blank=True, to='product.colorvariant'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_variant',
            field=models.ManyToManyField(blank=True, to='product.sizevariant'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
