# Generated by Django 5.1.6 on 2025-07-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cart_cartitem'),
        ('product', '0005_coupon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CartItems',
        ),
    ]
